CREATE TABLE MATCHES(
	ID_MATCH VARCHAR (50),
	PAST_MATCH VARCHAR (100),
	CURR_MATCH VARCHAR (100),
	NEXT_MATCH VARCHAR (100),
	
	PRIMARY KEY (ID_MATCH)
);

CREATE TABLE TEAMS(
	ID_TEAM VARCHAR (50),
	NAME_TEAM VARCHAR (100),
	MOTTO_TEAM VARCHAR (100),
	ID_MATCH VARCHAR (100),
	
	PRIMARY KEY (ID_TEAM),
	FOREIGN KEY (ID_MATCH) REFERENCES MATCHES
);

CREATE TABLE PLAYER(
	ID_PLAYER VARCHAR (50),
	NAME_PLAYER VARCHAR (100),
	NUM_PLAYER INT,
	POSITION_PLAYER CHAR (20),
	ID_TEAM VARCHAR (50),
	
	PRIMARY KEY (ID_PLAYER),
	FOREIGN KEY (ID_TEAM) REFERENCES TEAMS
);

CREATE TABLE _USER(
	ID_USER VARCHAR (50),
	NAME_USER VARCHAR (50),
	ADDRESS VARCHAR (50),
	PASSKEY VARCHAR (50),
	ROLE_USER VARCHAR (50),
	TOKEN_AUTH VARCHAR (50),
	
	PRIMARY KEY (ID_USER)
);


